apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1 
  labels:
    type: sample-webapp
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/jenkins/workspace/company-repo"