apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-webapp
  namespace: recurring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi